### ISSUE TITLE
Always return the message "Cleanup of sandbox * failed"

### ISSUE THREAD

**Issue by neyio** [judge0/api#143]
http://47.114.58.131:3000/dummy-client.html  version 1.5.0 via docker-compose up.

-----
I deployed on the Server .Also, I deployed on my Mac. Always return the message "Cleanup of sandbox * failed", no matter the lang is  C or Javascript.

Is there sth wrong?  such as  dir missing or permission deny.  Help me, thanks. 
------
The request:

```
[Request 2020/2/26 下午10:27:34] POST http://47.114.58.131:3000/submissions
{
    "source_code": "#include <stdio.h>\n\nint main(void) {\n  char name[10];\n  scanf(\"%s\", name);\n  printf(\"hello, %s\\n\", name);\n  return 0;\n}",
    "language_id": "49",
    "number_of_runs": "1",
    "stdin": "Judge0",
    "expected_output": "hello, Judge0",
    "cpu_time_limit": "2",
    "cpu_extra_time": "0.5",
    "wall_time_limit": "5",
    "memory_limit": "128000",
    "stack_limit": "64000",
    "max_processes_and_or_threads": "30",
    "enable_per_process_and_thread_time_limit": false,
    "enable_per_process_and_thread_memory_limit": true,
    "max_file_size": "1024"
}
[Response 2020/2/26 下午10:27:34] 201 Created
{
    "token": "2d365e4c-b74f-4d0d-876b-beab4baa5d05"
}
```
```
[Request 2020/2/26 下午10:27:35] GET http://47.114.58.131:3000/submissions/2d365e4c-b74f-4d0d-876b-beab4baa5d05
[Response 2020/2/26 下午10:27:35] 200 OK
{
    "stdout": "hello, Judge0\n",
    "time": "0.0",
    "memory": 604,
    "stderr": null,
    "token": "2d365e4c-b74f-4d0d-876b-beab4baa5d05",
    "compile_output": null,
    "message": "Cleanup of sandbox 38 failed.",
    "status": {
        "id": 13,
        "description": "Internal Error"
    }
}

[DONE 2020/2/26 下午10:27:35]

```

**Comment by neyio** [comment]
I checked logs.
```logs
api_1     | [2020-02-26T15:06:17+00:00] Running submission e8811045-4586-43f0-b05d-2a51afb13caf (40):
api_1     | isolate --cg -s -b 40 -M /var/local/lib/isolate/40/metadata.txt -t 2.0 -x 0.5 -w 5.0 -k 64000 -p30 --cg-mem=128000 --no-cg-timing -f 1024 -E HOME=/var/local/lib/isolate/40 -E PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" -E LANG -E LANGUAGE -E LC_ALL -E JUDGE0_HOMEPAGE -E JUDGE0_SOURCE_CODE -E JUDGE0_MAINTAINER -E JUDGE0_VERSION -d /etc:noexec --run -- /bin/bash run < /var/local/lib/isolate/40/stdin.txt > /var/local/lib/isolate/40/stdout.txt 2> /var/local/lib/isolate/40/stderr.txt 
api_1     | Cannot rmdir /var/local/lib/isolate/40: Directory not empty
api_1     | [ActiveJob] [IsolateJob] [aee0fb1e-e79d-4ee7-a128-122d33ba006e]    (0.2ms)  BEGIN
api_1     | [ActiveJob] [IsolateJob] [aee0fb1e-e79d-4ee7-a128-122d33ba006e]   Language Exists (0.3ms)  SELECT  1 AS one FROM "languages" WHERE "languages"."id" = $1 LIMIT $2  [["id", 49], ["LIMIT", 1]]
api_1     | [ActiveJob] [IsolateJob] [aee0fb1e-e79d-4ee7-a128-122d33ba006e]   CACHE (0.0ms)  SELECT  "languages".* FROM "languages" WHERE "languages"."id" = $1 LIMIT $2  [["id", 49], ["LIMIT", 1]]
api_1     | [ActiveJob] [IsolateJob] [aee0fb1e-e79d-4ee7-a128-122d33ba006e]   SQL (0.4ms)  UPDATE "submissions" SET "stdout" = $1, "status_id" = $2, "finished_at" = $3, "time" = $4, "memory" = $5, "exit_code" = $6, "message" = $7, "wall_time" = $8 WHERE "submissions"."id" = $9  [["stdout", "aGVsbG8sIEp1ZGdlMAo=\n"], ["status_id", 13], ["finished_at", "2020-02-26 15:06:17.746912"], ["time", "0.0"], ["memory", 24928], ["exit_code", 0], ["message", "Cleanup of sandbox 40 failed."], ["wall_time", "0.03"], ["id", 40]]
api_1     | [ActiveJob] [IsolateJob] [aee0fb1e-e79d-4ee7-a128-122d33ba006e]    (0.8ms)  COMMIT
api_1     | chown: cannot access '/var/local/lib/isolate/40/box': No such file or directory
api_1     | [ActiveJob] [IsolateJob] [aee0fb1e-e79d-4ee7-a128-122d33ba006e] Performed IsolateJob from Resque(default) in 599.99ms
api_1     | [active_model_serializers] Rendered SubmissionSerializer with ActiveModelSerializers::Adapter::Attributes (6.28ms)
api_1     | Completed 201 Created in 653ms (Views: 18.4ms | ActiveRecord: 7.8ms)
```

**Comment by neyio** [comment]
Okay, em. I find it in 
[Pull Request ](https://github.com/judge0/api/blob/84994af7049f275b7007d80a5a9d01c0e7df358e/app/jobs/isolate_job.rb)
So i copied the file to the dir  ` ./judge0-api-v1.5.0` and changed the file `docker-compose.yml` as blow.

```yml
version: "2"
services:
  api:
    image: judge0/api:1.5.0
    volumes:
      - ./judge0-api.conf:/judge0-api.conf:ro
      - ./isolate_job.rb:/api/app/jobs/isolate_job.rb
    ports:
      - "3000:3000"
    privileged: true
    restart: always

  worker:
    image: judge0/api:1.5.0
    command: ["./scripts/run-workers"]
    volumes:
      - ./judge0-api.conf:/judge0-api.conf:ro
      - ./isolate_job.rb:/api/app/jobs/isolate_job.rb
    privileged: true
    restart: always

  db:
    image: postgres:9.6
    env_file: judge0-api.conf
    volumes:
      - ./srv/postgres-data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:4.0
    command:
      [
        "bash",
        "-c",
        'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"',
      ]
    env_file: judge0-api.conf
    volumes:
      - ./srv/redis-data:/data
    restart: always

```

After next release version , close the issue pls. 
Sorry for disturbing.
