### ISSUE TITLE
Problem with deploying Judge0 with HTTPS

### ISSUE THREAD

**Issue by praveenkumar-alpha** [judge0/api#195]
This is my docker-compose.yml where i have changed the `VIRTUAL_HOST`, `LETSENCRYPT_HOST` and `LETSENCRYPT_EMAIL`.

```
version: '2'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  nginx:
    image: judge0/jwilder-nginx-proxy:latest-2020-02-11
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./srv/nginx/vhost.d:/etc/nginx/vhost.d
      - ./srv/nginx/html:/usr/share/nginx/html
      - ./srv/ssl_certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    <<: *default-logging
    restart: always

  letsencrypt:
    image: judge0/jrcs-letsencrypt-nginx-proxy-companion:v1.12.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./srv/ssl_certs:/etc/nginx/certs:rw
    volumes_from:
      - nginx
    <<: *default-logging
    restart: always

  server:
    image: judge0/api:1.9.0
    environment:
      - VIRTUAL_HOST=lbc.example.com
      - LETSENCRYPT_HOST=lbc.example.com
      - LETSENCRYPT_EMAIL=********************@gmail.com
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  workers:
    image: judge0/api:1.9.0
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:9.6
    env_file: judge0.conf
    volumes:
      - ./srv/postgres-data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:4.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    volumes:
      - ./srv/redis-data:/data
    <<: *default-logging
    restart: always
```

but when i try to access the judge0 in my browser it return page not found error. (gave correct and valid email ID)
