### ISSUE TITLE
Problem with setup : Postgres - could not connect to server

### ISSUE THREAD

**Issue by yuvrajsingla** [judge0/api#20]
I am getting the following error when I try to run the docker container. This is with fresh install on OS X. Got similar error with Ubuntu 16.04 (AWS EC2 instance).
  
> could not connect to server: Connection refused
> 	Is the server running on host "localhost" (::1) and accepting
> 	TCP/IP connections on port 5432?

**Comment by hermanzdosilovic** [comment]
What `docker-compose` file are you using? Did you follow this quide: https://github.com/judge0/api#quick-production-setup?

**Comment by yuvrajsingla** [comment]
Yes, followed the 'quick production steps', So using the docker-compose production file. Here's some details of the docker setup -> 
docker-compose version - 1.8.0, build unknown
docker version - 17.03.1-ce

**Comment by hermanzdosilovic** [comment]
As I can see, Rails is trying to connect to `localhost:5432` which doesn't exist. It should try connect to `db:5432` as specified in this line: https://github.com/judge0/api/blob/master/judge0-api.conf#L45.

Make sure that `RAILS_ENV` is set to `production`, `POSTGRES_HOST` is set to `db` (which is the name of service in `docker-compose.prod.yml`) and that `REDIS_HOST` is set to `redis` (which is the name of redis service in `docker-compose.prod.yml`).

Also, make sure that on server files `docker-compose.yml` and `judge0-api.conf` are in the same folder.

If it still doesn't work, please try adding `links` directive in Compose file, so that final `docker-compose.yml` on your server looks like this:
```
version: '2'
services:
  api:
    image: judge0/api
    env_file: judge0-api.conf
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    restart: always

  worker:
    image: judge0/api
    env_file: judge0-api.conf
    command: rails resque:work
    links:
      - db
      - redis
    privileged: true
    restart: always

  db:
    image: postgres
    env_file: judge0-api.conf
    volumes:
      - ./srv/postgres-data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - ./srv/redis-data:/data
    restart: always
```
